# Generated by Django 4.2.10 on 2024-02-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_items',
            field=models.JSONField(default=dict),
        ),
    ]
