# Generated by Django 4.2.10 on 2024-02-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
