# Generated by Django 4.2.10 on 2024-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_customer_orders_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_items',
            field=models.JSONField(default=list),
        ),
    ]
